#!/bin/sh

git fetch
latest="$(git ls-tree -r origin/main --name-only | grep '^migrations/' | cut -d/ -f2 | cut -d_ -f1 | grep '^00' | sort | tail -n1)"
if [ -n "$latest" ]; then
  echo "$latest"
else
  echo "0"
fi
