events {}
http {
    server_tokens off;

    # Access Logs for ALP https://github.com/tkuchiki/alp
    log_format json escape=json '{"time":"$time_local",'
                                '"host":"$remote_addr",'
                                '"forwardedfor":"$http_x_forwarded_for",'
                                '"req":"$request",'
                                '"status":"$status",'
                                '"method":"$request_method",'
                                '"uri":"$request_uri",'
                                '"body_bytes":$body_bytes_sent,'
                                '"referer":"$http_referer",'
                                '"ua":"$http_user_agent",'
                                '"request_time":$request_time,'
                                '"cache":"$upstream_http_x_cache",'
                                '"runtime":"$upstream_http_x_runtime",'
                                '"response_time":"$upstream_response_time",'
                                '"request_id":"$request_id",'
                                '"upstream_cache_status":"$upstream_cache_status",'
                                '"vhost":"$host"}';

    error_log /var/log/nginx/error.log warn;
    access_log /var/log/nginx/access.log json;

    proxy_cache_path /var/cache/nginx keys_zone=static:2m max_size=4g inactive=24h;
    proxy_temp_path /var/cache/nginx_tmp;

    server {
        client_max_body_size 10M;
        listen 80;

        set_real_ip_from 0.0.0.0/0;
        real_ip_header X-Forwarded-For;
        real_ip_recursive off;

        add_header X-Frame-Options DENY always;
        add_header X-Content-Type-Options nosniff always;
        add_header X-XSS-Protection "1; mode=block" always;
        add_header Strict-Transport-Security max-age=31536000 always;

        proxy_http_version 1.1;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Request-Id $request_id;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For "$http_x_forwarded_for, $realip_remote_addr";
        proxy_set_header X-Forwarded-Proto $scheme;

        location /_next/static {
            proxy_cache static;
            add_header X-Cache-Status $upstream_cache_status;
            add_header X-Frame-Options DENY always;
            add_header X-Content-Type-Options nosniff always;
            add_header X-XSS-Protection "1; mode=block" always;
            add_header Strict-Transport-Security max-age=31536000 always;
            proxy_pass http://localhost:4001;
        }

        location ~* ^/.*\\.(?:jpg|jpeg|gif|png|ico|cur|gz|svg|ttf)$ {
            proxy_cache static;
            proxy_ignore_headers Cache-Control;
            proxy_cache_valid 60m;
            add_header X-Cache-Status $upstream_cache_status;
            add_header X-Frame-Options DENY always;
            add_header X-Content-Type-Options nosniff always;
            add_header X-XSS-Protection "1; mode=block" always;
            add_header Strict-Transport-Security max-age=31536000 always;
            proxy_pass http://localhost:4001;
        }

        location /health {
            access_log off;
            proxy_pass http://localhost:4001;
        }

        location / {
            proxy_pass http://localhost:4001;
        }
    }
}
